@startuml create-user
skinparam backgroundColor #DDDDDD
hide footbox
actor User
collections FlexupApp
control FlexupAPI
database FlexupDB
entity Keycloak
database KeycloakDB
==Création utilisateur==
User -> FlexupApp : Demande accès application
activate FlexupApp
FlexupApp -> FlexupAPI : Demande formulaire connexion
activate FlexupAPI
FlexupAPI -> FlexupApp : Retourne formulaire connexion
deactivate FlexupAPI
FlexupApp -> User : Retourne formulaire connexion
deactivate FlexupApp
User -> FlexupApp : Demande formulaire enregistrement
activate FlexupApp
FlexupApp -> FlexupAPI : Demande formulaire enregistrement
activate FlexupAPI
FlexupAPI -> FlexupApp : Retourne formulaire enregistrement
deactivate FlexupAPI
FlexupApp -> User : Retourne formulaire enregistrement
deactivate FlexupApp
User -> FlexupApp : Soumission formulaire
activate FlexupApp
FlexupApp -> FlexupAPI : Soumission informations utilisateur
activate FlexupAPI
FlexupAPI -> FlexupDB : Recherche utilisateur
alt Utilisateur existant
activate FlexupDB
FlexupDB -> FlexupAPI : Utilisateur existant
destroy FlexupDB
FlexupAPI -> FlexupApp : Utilisateur existant
destroy FlexupAPI
FlexupApp -> User : Utilisateur existant
destroy FlexupApp
else Utilisateur non existant
activate FlexupDB
FlexupDB -> FlexupAPI : Utilisateur non existant
deactivate FlexupDB
activate FlexupAPI
FlexupAPI -> Keycloak : Demande enregistrement utilisateur
activate Keycloak
Keycloak -> KeycloakDB : Persistance utilisateur
activate KeycloakDB
KeycloakDB -> Keycloak : Retourne enregistrement utilisateur
deactivate KeycloakDB
Keycloak -> FlexupAPI : Retourne informations utilisateur
deactivate Keycloak
FlexupAPI -> FlexupDB : Persistance profil
activate FlexupDB
FlexupDB -> FlexupAPI : Retourne profil
deactivate FlexupDB
==Création compte==
FlexupAPI -> FlexupDB : Persistance compte basé sur profil
activate FlexupDB
FlexupDB -> FlexupAPI : Retourne enregistrement compte
deactivate FlexupDB
FlexupAPI -> FlexupApp : Retourne enregistrement compte
deactivate FlexupAPI
activate FlexupApp
FlexupApp -> User : Redirige vers page accueil compte
deactivate FlexupApp
end
@enduml
